version: "3.8"

services:
  # Serviço de desenvolvimento
  psicanakarla-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: psicanakarla-dev
    ports:
      - "3400:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    command: npm run dev
    profiles:
      - dev
    networks:
      - psicanakarla-network

  # Serviço de produção
  psicanakarla-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: psicanakarla-prod
    ports:
      - "3400:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    profiles:
      - prod
    networks:
      - psicanakarla-network

  # Serviço com nginx para produção (opcional)
  nginx:
    image: nginx:alpine
    container_name: psicanakarla-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - psicanakarla-prod
    profiles:
      - prod
      - nginx
    networks:
      - psicanakarla-network

networks:
  psicanakarla-network:
    driver: bridge

volumes:
  node_modules:
  next_cache:
